# Generated by Django 4.2.25 on 2026-04-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_quickly',
            field=models.BooleanField(default=False),
        ),
    ]
