# Generated by Django 4.2.25 on 2026-04-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_task_is_quickly'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('work', 'Работа'), ('education', 'Образование'), ('other', 'Другое')], default='other', max_length=20),
        ),
    ]
