# Generated by Django 4.2.25 on 2026-04-26 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_task_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='discription',
            new_name='description',
        ),
    ]
